### ISSUE TITLE
Remove `engines` from package.json or add node.

### ISSUE THREAD

**Issue by pospi** [jclem/koa-ssl#1]
This module won't install with Yarn- it seems to be more particular about checking these flags than the NPM client. The following error is given:

```
error koa-ssl@2.0.0: The engine "node" is incompatible with this module. Expected version "1.2.0".
```

It can be worked around temporarily by using `yarn --ignore-engines` in your parent application module when installing.

**Comment by rkkautsar** [comment]
:up:

**Comment by pdroll** [comment]
🆙

**Comment by nic** [comment]
🆙

**Comment by DenisGorbachev** [comment]
:up:

**Comment by joeyfigaro** [comment]
[PR has been put up for this](https://github.com/jclem/koa-ssl/pull/2).
